# ===================================================================
# Spring Booot开发环境配置
# ===================================================================

spring:
  thymeleaf:
    cache: false  # thymeleaf模板引擎是否开启缓存，开发时关闭
    mode: LEGACYHTML5
  jpa:
    database: mysql
    show-sql: true  #显示执行sql
    hibernate:
      ddl-auto: update  # 数据库的表和列会自动创建
  # 数据库访问配置
  datasource:
    # 主数据源
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.36.38:3306/zj_industry_bigdata?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    # 下面为连接池的补充设置，应用到上面所有数据源中
    initial-size: 2                           # 连接池初始化大小
    min-idle: 2                               # 最小连接池
    max-active: 10                            # 最大连接池
    max-wait: 6000                            # 配置获取连接等待超时的时间6000ms
    time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    min-evictable-idle-time-millis: 300000    # 配置一个连接在池中最小生存的时间，单位是毫秒
    validation-query: SELECT 1 FROM USER
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true            # 打开PSCache
    max-open-prepared-statements: 20          # 并且指定每个连接上PSCache的大小
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    filters: stat,wall,log4j                  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  jmx: # 必须关闭jms，否则启动报错
    enabled: false

# ===================================================================
# durid监控配置
# ===================================================================
#durid:
#  WebInitParam:
#    allow: 127.0.0.1 # IP白名单 (没有配置或者为空，则允许所有访问)
#    deny:

# ===================================================================
# Eureka注册中心配置
# ===================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

# ===================================================================
# Logback开发环境日志输出
# ===================================================================
logging:
  file: out/admin-dev.log
  level:
    com.qtdbp.trading: TRACE

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  soTimeout: 1501
  connectTimeout: 601
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 192.168.36.39:22122
    #- 192.168.36.39:22123
  pool:
      #从池中借出的对象的最大数目
      maxTotal: 50
      #获取连接时的最大等待毫秒数100
      maxWaitMillis: 100
