# bootstrap.yml 先于 application.yml 加载；所以配置服务要先加载，否则报错


# ===================================================================
# 消息总线RabbitMQ配置
# ===================================================================
rabbitmq:
  host: ${rabbitmq.host}
  port: ${rabbitmq.port}
  username: ${rabbitmq.username}
  password: ${rabbitmq.password}

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  soTimeout: 1501
  connectTimeout: 601
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 192.168.36.39:22122
    #- 192.168.36.39:22123
  pool:
      #从池中借出的对象的最大数目
      maxTotal: 153
      #获取连接时的最大等待毫秒数100
      maxWaitMillis: 102
## 必须关闭jms，否则启动报错
spring:
  jmx:
    enabled: false

# fdfs upload 文件上传配置信息
fdfs-upload:
  port: 2300
  host: 192.168.36.39