package com.qtdbp.trading.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 订单
 */
public class DataTransactionOrderModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.product_type
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private Byte productType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.product_id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.user_id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.sell_user_id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private Integer sellUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.order_no
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private String orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.amount
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private BigDecimal amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.order_state
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private Byte orderState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.addtime
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private Date addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.pay_time
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.finish_time
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private Date finishTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.editor_id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private Integer editorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.editor_time
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private Date editorTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.pay_way
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private Byte payWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.receive_name
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private String receiveName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.contact_phone
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private String contactPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_transaction_order.pay_way_content
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	private String payWayContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.id
	 * @return  the value of data_transaction_order.id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.id
	 * @param id  the value for data_transaction_order.id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.product_type
	 * @return  the value of data_transaction_order.product_type
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public Byte getProductType() {
		return productType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.product_type
	 * @param productType  the value for data_transaction_order.product_type
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setProductType(Byte productType) {
		this.productType = productType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.product_id
	 * @return  the value of data_transaction_order.product_id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.product_id
	 * @param productId  the value for data_transaction_order.product_id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.user_id
	 * @return  the value of data_transaction_order.user_id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.user_id
	 * @param userId  the value for data_transaction_order.user_id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.sell_user_id
	 * @return  the value of data_transaction_order.sell_user_id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public Integer getSellUserId() {
		return sellUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.sell_user_id
	 * @param sellUserId  the value for data_transaction_order.sell_user_id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setSellUserId(Integer sellUserId) {
		this.sellUserId = sellUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.order_no
	 * @return  the value of data_transaction_order.order_no
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public String getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.order_no
	 * @param orderNo  the value for data_transaction_order.order_no
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.amount
	 * @return  the value of data_transaction_order.amount
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.amount
	 * @param amount  the value for data_transaction_order.amount
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.order_state
	 * @return  the value of data_transaction_order.order_state
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public Byte getOrderState() {
		return orderState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.order_state
	 * @param orderState  the value for data_transaction_order.order_state
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setOrderState(Byte orderState) {
		this.orderState = orderState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.addtime
	 * @return  the value of data_transaction_order.addtime
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.addtime
	 * @param addtime  the value for data_transaction_order.addtime
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.pay_time
	 * @return  the value of data_transaction_order.pay_time
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.pay_time
	 * @param payTime  the value for data_transaction_order.pay_time
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.finish_time
	 * @return  the value of data_transaction_order.finish_time
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public Date getFinishTime() {
		return finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.finish_time
	 * @param finishTime  the value for data_transaction_order.finish_time
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.editor_id
	 * @return  the value of data_transaction_order.editor_id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public Integer getEditorId() {
		return editorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.editor_id
	 * @param editorId  the value for data_transaction_order.editor_id
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setEditorId(Integer editorId) {
		this.editorId = editorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.editor_time
	 * @return  the value of data_transaction_order.editor_time
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public Date getEditorTime() {
		return editorTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.editor_time
	 * @param editorTime  the value for data_transaction_order.editor_time
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setEditorTime(Date editorTime) {
		this.editorTime = editorTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.pay_way
	 * @return  the value of data_transaction_order.pay_way
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public Byte getPayWay() {
		return payWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.pay_way
	 * @param payWay  the value for data_transaction_order.pay_way
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setPayWay(Byte payWay) {
		this.payWay = payWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.receive_name
	 * @return  the value of data_transaction_order.receive_name
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public String getReceiveName() {
		return receiveName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.receive_name
	 * @param receiveName  the value for data_transaction_order.receive_name
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setReceiveName(String receiveName) {
		this.receiveName = receiveName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.contact_phone
	 * @return  the value of data_transaction_order.contact_phone
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public String getContactPhone() {
		return contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.contact_phone
	 * @param contactPhone  the value for data_transaction_order.contact_phone
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_transaction_order.pay_way_content
	 * @return  the value of data_transaction_order.pay_way_content
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public String getPayWayContent() {
		return payWayContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_transaction_order.pay_way_content
	 * @param payWayContent  the value for data_transaction_order.pay_way_content
	 * @mbggenerated  Wed Aug 12 15:32:38 CST 2015
	 */
	public void setPayWayContent(String payWayContent) {
		this.payWayContent = payWayContent;
	}
}