package com.qtdbp.trading.model;

import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * 数据众包Model
 */
public class DataBuyInfoModel extends BaseModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.designation
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String designation;
	/**
	 * 详情内容
	 */
	private String description ;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.subject_type
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Byte subjectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.data_pattern
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Byte dataPattern;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.data_type
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Integer dataType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.from_date
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Date fromDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.to_date
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Date toDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.data_scale
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Double dataScale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.unit
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Byte unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.user_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.addtime
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	@ApiModelProperty(hidden = true)
	private Date addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.editor_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	@ApiModelProperty(hidden = true)
	private Integer editorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.editor_time
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	@ApiModelProperty(hidden = true)
	private Date editorTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.contacts_name
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String contactsName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.contacts_phone
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String contactsPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.contacts_email
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String contactsEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.is_used
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	@ApiModelProperty(hidden = true)
	private Byte isUsed;
	/**
	 * 预期费用
	 */
	private Double expFee ;

	private Integer dataTypeSub ;

	public String getDesignation() {
		return designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Byte getSubjectType() {
		return subjectType;
	}

	public void setSubjectType(Byte subjectType) {
		this.subjectType = subjectType;
	}

	public Byte getDataPattern() {
		return dataPattern;
	}

	public void setDataPattern(Byte dataPattern) {
		this.dataPattern = dataPattern;
	}

	public Integer getDataType() {
		return dataType;
	}

	public void setDataType(Integer dataType) {
		this.dataType = dataType;
	}

	public Date getFromDate() {
		return fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public Double getDataScale() {
		return dataScale;
	}

	public void setDataScale(Double dataScale) {
		this.dataScale = dataScale;
	}

	public Byte getUnit() {
		return unit;
	}

	public void setUnit(Byte unit) {
		this.unit = unit;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Date getAddtime() {
		return addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public Integer getEditorId() {
		return editorId;
	}

	public void setEditorId(Integer editorId) {
		this.editorId = editorId;
	}

	public Date getEditorTime() {
		return editorTime;
	}

	public void setEditorTime(Date editorTime) {
		this.editorTime = editorTime;
	}

	public String getContactsName() {
		return contactsName;
	}

	public void setContactsName(String contactsName) {
		this.contactsName = contactsName;
	}

	public String getContactsPhone() {
		return contactsPhone;
	}

	public void setContactsPhone(String contactsPhone) {
		this.contactsPhone = contactsPhone;
	}

	public String getContactsEmail() {
		return contactsEmail;
	}

	public void setContactsEmail(String contactsEmail) {
		this.contactsEmail = contactsEmail;
	}

	public Byte getIsUsed() {
		return isUsed;
	}

	public void setIsUsed(Byte isUsed) {
		this.isUsed = isUsed;
	}

	public Double getExpFee() {
		return expFee;
	}

	public void setExpFee(Double expFee) {
		this.expFee = expFee;
	}

	public Integer getDataTypeSub() {
		return dataTypeSub;
	}

	public void setDataTypeSub(Integer dataTypeSub) {
		this.dataTypeSub = dataTypeSub;
	}
}