package com.qtdbp.trading.model;

import java.util.Date;

/**
 * 数据众包Model
 */
public class DataBuyInfoModel extends BaseModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.designation
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String designation;

	/**
	 * 详情内容
	 */
	private String description ;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.subject_type
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Byte subjectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.data_pattern
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Byte dataPattern;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.suffix
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String suffix;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.data_language
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Byte dataLanguage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.data_achieve_way
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Byte dataAchieveWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.cost_budget
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Double costBudget;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.data_type
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Integer dataType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.from_date
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Date fromDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.to_date
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Date toDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.cooperate_way
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Byte cooperateWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.buy_way
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Byte buyWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.fee
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Double fee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.data_scale
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Double dataScale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.unit
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Byte unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.province_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Integer provinceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.city_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Integer cityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.data_source
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String dataSource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.copyright_info
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String copyrightInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.data_declare
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String dataDeclare;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.fact_pic1
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String factPic1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.fact_pic2
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String factPic2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.fact_pic3
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String factPic3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.fact_pic4
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String factPic4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.fact_pic5
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String factPic5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.fact_pic6
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String factPic6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.address
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.user_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.addtime
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Date addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.editor_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Integer editorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.editor_time
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Date editorTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.contacts_name
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String contactsName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.contacts_phone
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String contactsPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.contacts_email
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String contactsEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.contacts_QQ
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String contactsQq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.contacts_address
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private String contactsAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_buy_base_info.is_used
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	private Byte isUsed;

	/**
	 * 预期费用
	 */
	private Double expFee ;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.id
	 * @return  the value of data_buy_base_info.id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.id
	 * @param id  the value for data_buy_base_info.id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.designation
	 * @return  the value of data_buy_base_info.designation
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getDesignation() {
		return designation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.designation
	 * @param designation  the value for data_buy_base_info.designation
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setDesignation(String designation) {
		this.designation = designation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.subject_type
	 * @return  the value of data_buy_base_info.subject_type
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Byte getSubjectType() {
		return subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.subject_type
	 * @param subjectType  the value for data_buy_base_info.subject_type
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setSubjectType(Byte subjectType) {
		this.subjectType = subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.data_pattern
	 * @return  the value of data_buy_base_info.data_pattern
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Byte getDataPattern() {
		return dataPattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.data_pattern
	 * @param dataPattern  the value for data_buy_base_info.data_pattern
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setDataPattern(Byte dataPattern) {
		this.dataPattern = dataPattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.suffix
	 * @return  the value of data_buy_base_info.suffix
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getSuffix() {
		return suffix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.suffix
	 * @param suffix  the value for data_buy_base_info.suffix
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.data_language
	 * @return  the value of data_buy_base_info.data_language
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Byte getDataLanguage() {
		return dataLanguage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.data_language
	 * @param dataLanguage  the value for data_buy_base_info.data_language
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setDataLanguage(Byte dataLanguage) {
		this.dataLanguage = dataLanguage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.data_achieve_way
	 * @return  the value of data_buy_base_info.data_achieve_way
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Byte getDataAchieveWay() {
		return dataAchieveWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.data_achieve_way
	 * @param dataAchieveWay  the value for data_buy_base_info.data_achieve_way
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setDataAchieveWay(Byte dataAchieveWay) {
		this.dataAchieveWay = dataAchieveWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.cost_budget
	 * @return  the value of data_buy_base_info.cost_budget
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Double getCostBudget() {
		return costBudget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.cost_budget
	 * @param costBudget  the value for data_buy_base_info.cost_budget
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setCostBudget(Double costBudget) {
		this.costBudget = costBudget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.data_type
	 * @return  the value of data_buy_base_info.data_type
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Integer getDataType() {
		return dataType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.data_type
	 * @param dataType  the value for data_buy_base_info.data_type
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setDataType(Integer dataType) {
		this.dataType = dataType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.from_date
	 * @return  the value of data_buy_base_info.from_date
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Date getFromDate() {
		return fromDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.from_date
	 * @param fromDate  the value for data_buy_base_info.from_date
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.to_date
	 * @return  the value of data_buy_base_info.to_date
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Date getToDate() {
		return toDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.to_date
	 * @param toDate  the value for data_buy_base_info.to_date
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.cooperate_way
	 * @return  the value of data_buy_base_info.cooperate_way
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Byte getCooperateWay() {
		return cooperateWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.cooperate_way
	 * @param cooperateWay  the value for data_buy_base_info.cooperate_way
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setCooperateWay(Byte cooperateWay) {
		this.cooperateWay = cooperateWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.buy_way
	 * @return  the value of data_buy_base_info.buy_way
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Byte getBuyWay() {
		return buyWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.buy_way
	 * @param buyWay  the value for data_buy_base_info.buy_way
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setBuyWay(Byte buyWay) {
		this.buyWay = buyWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.fee
	 * @return  the value of data_buy_base_info.fee
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Double getFee() {
		return fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.fee
	 * @param fee  the value for data_buy_base_info.fee
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setFee(Double fee) {
		this.fee = fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.data_scale
	 * @return  the value of data_buy_base_info.data_scale
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Double getDataScale() {
		return dataScale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.data_scale
	 * @param dataScale  the value for data_buy_base_info.data_scale
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setDataScale(Double dataScale) {
		this.dataScale = dataScale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.unit
	 * @return  the value of data_buy_base_info.unit
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Byte getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.unit
	 * @param unit  the value for data_buy_base_info.unit
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setUnit(Byte unit) {
		this.unit = unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.province_id
	 * @return  the value of data_buy_base_info.province_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Integer getProvinceId() {
		return provinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.province_id
	 * @param provinceId  the value for data_buy_base_info.province_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.city_id
	 * @return  the value of data_buy_base_info.city_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.city_id
	 * @param cityId  the value for data_buy_base_info.city_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.data_source
	 * @return  the value of data_buy_base_info.data_source
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getDataSource() {
		return dataSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.data_source
	 * @param dataSource  the value for data_buy_base_info.data_source
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setDataSource(String dataSource) {
		this.dataSource = dataSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.copyright_info
	 * @return  the value of data_buy_base_info.copyright_info
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getCopyrightInfo() {
		return copyrightInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.copyright_info
	 * @param copyrightInfo  the value for data_buy_base_info.copyright_info
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setCopyrightInfo(String copyrightInfo) {
		this.copyrightInfo = copyrightInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.data_declare
	 * @return  the value of data_buy_base_info.data_declare
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getDataDeclare() {
		return dataDeclare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.data_declare
	 * @param dataDeclare  the value for data_buy_base_info.data_declare
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setDataDeclare(String dataDeclare) {
		this.dataDeclare = dataDeclare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.fact_pic1
	 * @return  the value of data_buy_base_info.fact_pic1
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getFactPic1() {
		return factPic1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.fact_pic1
	 * @param factPic1  the value for data_buy_base_info.fact_pic1
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setFactPic1(String factPic1) {
		this.factPic1 = factPic1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.fact_pic2
	 * @return  the value of data_buy_base_info.fact_pic2
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getFactPic2() {
		return factPic2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.fact_pic2
	 * @param factPic2  the value for data_buy_base_info.fact_pic2
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setFactPic2(String factPic2) {
		this.factPic2 = factPic2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.fact_pic3
	 * @return  the value of data_buy_base_info.fact_pic3
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getFactPic3() {
		return factPic3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.fact_pic3
	 * @param factPic3  the value for data_buy_base_info.fact_pic3
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setFactPic3(String factPic3) {
		this.factPic3 = factPic3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.fact_pic4
	 * @return  the value of data_buy_base_info.fact_pic4
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getFactPic4() {
		return factPic4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.fact_pic4
	 * @param factPic4  the value for data_buy_base_info.fact_pic4
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setFactPic4(String factPic4) {
		this.factPic4 = factPic4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.fact_pic5
	 * @return  the value of data_buy_base_info.fact_pic5
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getFactPic5() {
		return factPic5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.fact_pic5
	 * @param factPic5  the value for data_buy_base_info.fact_pic5
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setFactPic5(String factPic5) {
		this.factPic5 = factPic5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.fact_pic6
	 * @return  the value of data_buy_base_info.fact_pic6
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getFactPic6() {
		return factPic6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.fact_pic6
	 * @param factPic6  the value for data_buy_base_info.fact_pic6
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setFactPic6(String factPic6) {
		this.factPic6 = factPic6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.address
	 * @return  the value of data_buy_base_info.address
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.address
	 * @param address  the value for data_buy_base_info.address
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.user_id
	 * @return  the value of data_buy_base_info.user_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.user_id
	 * @param userId  the value for data_buy_base_info.user_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.addtime
	 * @return  the value of data_buy_base_info.addtime
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.addtime
	 * @param addtime  the value for data_buy_base_info.addtime
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.editor_id
	 * @return  the value of data_buy_base_info.editor_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Integer getEditorId() {
		return editorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.editor_id
	 * @param editorId  the value for data_buy_base_info.editor_id
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setEditorId(Integer editorId) {
		this.editorId = editorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.editor_time
	 * @return  the value of data_buy_base_info.editor_time
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Date getEditorTime() {
		return editorTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.editor_time
	 * @param editorTime  the value for data_buy_base_info.editor_time
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setEditorTime(Date editorTime) {
		this.editorTime = editorTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.contacts_name
	 * @return  the value of data_buy_base_info.contacts_name
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getContactsName() {
		return contactsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.contacts_name
	 * @param contactsName  the value for data_buy_base_info.contacts_name
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setContactsName(String contactsName) {
		this.contactsName = contactsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.contacts_phone
	 * @return  the value of data_buy_base_info.contacts_phone
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getContactsPhone() {
		return contactsPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.contacts_phone
	 * @param contactsPhone  the value for data_buy_base_info.contacts_phone
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setContactsPhone(String contactsPhone) {
		this.contactsPhone = contactsPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.contacts_email
	 * @return  the value of data_buy_base_info.contacts_email
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getContactsEmail() {
		return contactsEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.contacts_email
	 * @param contactsEmail  the value for data_buy_base_info.contacts_email
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setContactsEmail(String contactsEmail) {
		this.contactsEmail = contactsEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.contacts_QQ
	 * @return  the value of data_buy_base_info.contacts_QQ
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getContactsQq() {
		return contactsQq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.contacts_QQ
	 * @param contactsQq  the value for data_buy_base_info.contacts_QQ
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setContactsQq(String contactsQq) {
		this.contactsQq = contactsQq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.contacts_address
	 * @return  the value of data_buy_base_info.contacts_address
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public String getContactsAddress() {
		return contactsAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.contacts_address
	 * @param contactsAddress  the value for data_buy_base_info.contacts_address
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setContactsAddress(String contactsAddress) {
		this.contactsAddress = contactsAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_buy_base_info.is_used
	 * @return  the value of data_buy_base_info.is_used
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public Byte getIsUsed() {
		return isUsed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_buy_base_info.is_used
	 * @param isUsed  the value for data_buy_base_info.is_used
	 * @mbggenerated  Thu Jul 30 10:44:04 CST 2015
	 */
	public void setIsUsed(Byte isUsed) {
		this.isUsed = isUsed;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getExpFee() {
		return expFee;
	}

	public void setExpFee(Double expFee) {
		this.expFee = expFee;
	}
}