package com.qtdbp.trading.model;

import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * 方案召集Model
 */
public class DataSosInfoModel extends BaseModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.id
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	@ApiModelProperty(hidden = true)
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.designation
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private String designation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.data_scale
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private Integer dataScale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.unit
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private Byte unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.dimension
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private Byte dimension;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.demand_type
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private Byte demandType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.from_date
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private Date fromDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.to_date
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private Date toDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.exp_fee
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private Double expFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.contacts_name
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private String contactsName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.contacts_phone
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private String contactsPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.contacts_email
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private String contactsEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.user_id
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.addtime
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	@ApiModelProperty(hidden = true)
	private Date addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.editor_id
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	@ApiModelProperty(hidden = true)
	private Integer editorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.editor_time
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	@ApiModelProperty(hidden = true)
	private Date editorTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.is_used
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	@ApiModelProperty(hidden = true)
	private Byte isUsed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.filePath
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private String filepath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.data_type
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private Integer dataType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.data_type_sub
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	@ApiModelProperty(hidden = true)
	private Integer dataTypeSub;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_sos_info.description
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.id
	 * @return  the value of data_sos_info.id
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.id
	 * @param id  the value for data_sos_info.id
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.designation
	 * @return  the value of data_sos_info.designation
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public String getDesignation() {
		return designation;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.designation
	 * @param designation  the value for data_sos_info.designation
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setDesignation(String designation) {
		this.designation = designation;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.data_scale
	 * @return  the value of data_sos_info.data_scale
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Integer getDataScale() {
		return dataScale;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.data_scale
	 * @param dataScale  the value for data_sos_info.data_scale
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setDataScale(Integer dataScale) {
		this.dataScale = dataScale;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.unit
	 * @return  the value of data_sos_info.unit
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Byte getUnit() {
		return unit;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.unit
	 * @param unit  the value for data_sos_info.unit
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setUnit(Byte unit) {
		this.unit = unit;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.dimension
	 * @return  the value of data_sos_info.dimension
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Byte getDimension() {
		return dimension;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.dimension
	 * @param dimension  the value for data_sos_info.dimension
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setDimension(Byte dimension) {
		this.dimension = dimension;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.demand_type
	 * @return  the value of data_sos_info.demand_type
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Byte getDemandType() {
		return demandType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.demand_type
	 * @param demandType  the value for data_sos_info.demand_type
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setDemandType(Byte demandType) {
		this.demandType = demandType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.from_date
	 * @return  the value of data_sos_info.from_date
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Date getFromDate() {
		return fromDate;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.from_date
	 * @param fromDate  the value for data_sos_info.from_date
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.to_date
	 * @return  the value of data_sos_info.to_date
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Date getToDate() {
		return toDate;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.to_date
	 * @param toDate  the value for data_sos_info.to_date
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.exp_fee
	 * @return  the value of data_sos_info.exp_fee
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Double getExpFee() {
		return expFee;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.exp_fee
	 * @param expFee  the value for data_sos_info.exp_fee
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setExpFee(Double expFee) {
		this.expFee = expFee;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.contacts_name
	 * @return  the value of data_sos_info.contacts_name
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public String getContactsName() {
		return contactsName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.contacts_name
	 * @param contactsName  the value for data_sos_info.contacts_name
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setContactsName(String contactsName) {
		this.contactsName = contactsName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.contacts_phone
	 * @return  the value of data_sos_info.contacts_phone
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public String getContactsPhone() {
		return contactsPhone;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.contacts_phone
	 * @param contactsPhone  the value for data_sos_info.contacts_phone
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setContactsPhone(String contactsPhone) {
		this.contactsPhone = contactsPhone;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.contacts_email
	 * @return  the value of data_sos_info.contacts_email
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public String getContactsEmail() {
		return contactsEmail;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.contacts_email
	 * @param contactsEmail  the value for data_sos_info.contacts_email
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setContactsEmail(String contactsEmail) {
		this.contactsEmail = contactsEmail;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.user_id
	 * @return  the value of data_sos_info.user_id
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.user_id
	 * @param userId  the value for data_sos_info.user_id
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.addtime
	 * @return  the value of data_sos_info.addtime
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Date getAddtime() {
		return addtime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.addtime
	 * @param addtime  the value for data_sos_info.addtime
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.editor_id
	 * @return  the value of data_sos_info.editor_id
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Integer getEditorId() {
		return editorId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.editor_id
	 * @param editorId  the value for data_sos_info.editor_id
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setEditorId(Integer editorId) {
		this.editorId = editorId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.editor_time
	 * @return  the value of data_sos_info.editor_time
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Date getEditorTime() {
		return editorTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.editor_time
	 * @param editorTime  the value for data_sos_info.editor_time
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setEditorTime(Date editorTime) {
		this.editorTime = editorTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.is_used
	 * @return  the value of data_sos_info.is_used
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Byte getIsUsed() {
		return isUsed;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.is_used
	 * @param isUsed  the value for data_sos_info.is_used
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setIsUsed(Byte isUsed) {
		this.isUsed = isUsed;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.filePath
	 * @return  the value of data_sos_info.filePath
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public String getFilepath() {
		return filepath;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.filePath
	 * @param filepath  the value for data_sos_info.filePath
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.data_type
	 * @return  the value of data_sos_info.data_type
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Integer getDataType() {
		return dataType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.data_type
	 * @param dataType  the value for data_sos_info.data_type
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setDataType(Integer dataType) {
		this.dataType = dataType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.data_type_sub
	 * @return  the value of data_sos_info.data_type_sub
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public Integer getDataTypeSub() {
		return dataTypeSub;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.data_type_sub
	 * @param dataTypeSub  the value for data_sos_info.data_type_sub
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setDataTypeSub(Integer dataTypeSub) {
		this.dataTypeSub = dataTypeSub;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_sos_info.description
	 * @return  the value of data_sos_info.description
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public String getDescription() {
		return description;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_sos_info.description
	 * @param description  the value for data_sos_info.description
	 * @mbggenerated  Tue Feb 23 15:27:30 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description;
	}

}
