package com.qtdbp.trading.model;

import java.util.Date;

/**
 * 需求订单
 */
public class DataAuthorizeOrderModel extends BaseModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_authorize_order.id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_authorize_order.product_type
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	private Byte productType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_authorize_order.base_id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	private Integer baseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_authorize_order.order_state
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	private Byte orderState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_authorize_order.user_id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_authorize_order.institution_id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	private Integer institutionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_authorize_order.addtime
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	private Date addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_authorize_order.editor_id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	private Integer editorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_authorize_order.editor_time
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	private Date editorTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_authorize_order.is_used
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	private Byte isUsed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column data_authorize_order.content
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	private String content;
	
	private String samplePath;

	
	public String getSamplePath() {
		return samplePath;
	}

	public void setSamplePath(String samplePath) {
		this.samplePath = samplePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_authorize_order.id
	 * @return  the value of data_authorize_order.id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_authorize_order.id
	 * @param id  the value for data_authorize_order.id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_authorize_order.product_type
	 * @return  the value of data_authorize_order.product_type
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public Byte getProductType() {
		return productType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_authorize_order.product_type
	 * @param productType  the value for data_authorize_order.product_type
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public void setProductType(Byte productType) {
		this.productType = productType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_authorize_order.base_id
	 * @return  the value of data_authorize_order.base_id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public Integer getBaseId() {
		return baseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_authorize_order.base_id
	 * @param baseId  the value for data_authorize_order.base_id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public void setBaseId(Integer baseId) {
		this.baseId = baseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_authorize_order.order_state
	 * @return  the value of data_authorize_order.order_state
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public Byte getOrderState() {
		return orderState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_authorize_order.order_state
	 * @param orderState  the value for data_authorize_order.order_state
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public void setOrderState(Byte orderState) {
		this.orderState = orderState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_authorize_order.user_id
	 * @return  the value of data_authorize_order.user_id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_authorize_order.user_id
	 * @param userId  the value for data_authorize_order.user_id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_authorize_order.institution_id
	 * @return  the value of data_authorize_order.institution_id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public Integer getInstitutionId() {
		return institutionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_authorize_order.institution_id
	 * @param institutionId  the value for data_authorize_order.institution_id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public void setInstitutionId(Integer institutionId) {
		this.institutionId = institutionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_authorize_order.addtime
	 * @return  the value of data_authorize_order.addtime
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_authorize_order.addtime
	 * @param addtime  the value for data_authorize_order.addtime
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_authorize_order.editor_id
	 * @return  the value of data_authorize_order.editor_id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public Integer getEditorId() {
		return editorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_authorize_order.editor_id
	 * @param editorId  the value for data_authorize_order.editor_id
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public void setEditorId(Integer editorId) {
		this.editorId = editorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_authorize_order.editor_time
	 * @return  the value of data_authorize_order.editor_time
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public Date getEditorTime() {
		return editorTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_authorize_order.editor_time
	 * @param editorTime  the value for data_authorize_order.editor_time
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public void setEditorTime(Date editorTime) {
		this.editorTime = editorTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_authorize_order.is_used
	 * @return  the value of data_authorize_order.is_used
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public Byte getIsUsed() {
		return isUsed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_authorize_order.is_used
	 * @param isUsed  the value for data_authorize_order.is_used
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public void setIsUsed(Byte isUsed) {
		this.isUsed = isUsed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column data_authorize_order.content
	 * @return  the value of data_authorize_order.content
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column data_authorize_order.content
	 * @param content  the value for data_authorize_order.content
	 * @mbggenerated  Fri Jul 10 09:18:44 CST 2015
	 */
	public void setContent(String content) {
		this.content = content;
	}
}