# ===================================================================
# Spring Booot开发环境配置
# ===================================================================

spring:
  thymeleaf:
    cache: false  # thymeleaf模板引擎是否开启缓存，开发时关闭
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 2 # 连接池初始化大小
    min-idle: 2     # 最小连接池
    max-active: 10  # 最大连接池
    max-wait: 600   # 配置获取连接等待超时的时间600ms
    time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    min-evictable-idle-time-millis: 300000   # 配置一个连接在池中最小生存的时间，单位是毫秒
    validation-query: SELECT 1 FROM USER
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    url: jdbc:mysql://192.168.36.38:3306/zj_industry_bigdata?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    pool-prepared-statements: true   # 打开PSCache
    max-open-prepared-statements: 20 # 并且指定每个连接上PSCache的大小
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    filters: stat,wall,log4j         # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙


# ===================================================================
# Eureka注册中心配置
# ===================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

# ===================================================================
# Logback开发环境日志输出
# ===================================================================
logging:
  file: out/my-dev.log
  level:
    com.qtdbp.trading: TRACE