# ===================================================================
# Spring Booot开发环境配置
# ===================================================================

spring:
  thymeleaf:
    cache: false  # thymeleaf模板引擎是否开启缓存，开发时关闭
    mode: LEGACYHTML5
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 2 # 连接池初始化大小
    min-idle: 2     # 最小连接池
    max-active: 10  # 最大连接池
    max-wait: 600   # 配置获取连接等待超时的时间600ms
    time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    min-evictable-idle-time-millis: 300000   # 配置一个连接在池中最小生存的时间，单位是毫秒
    validation-query: SELECT 1 FROM USER
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    url: jdbc:mysql://192.168.36.38:3306/zj_industry_bigdata?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    pool-prepared-statements: true   # 打开PSCache
    max-open-prepared-statements: 20 # 并且指定每个连接上PSCache的大小
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    filters: stat,wall,log4j         # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  jmx: # 必须关闭jms，否则启动报错
    enabled: false

# ===================================================================
# Eureka注册中心配置
# ===================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

# ===================================================================
# Logback开发环境日志输出
# ===================================================================
logging:
  file: out/my-dev.log
  level:
    com.qtdbp.trading: TRACE

# ===================================================================
# sso单点登录配置
# ===================================================================
sso:
  key: eada1cfcc5d247d49d3c3494b7360f24
  host: http://sso.qtbigdata.com/
  loginUrl: http://sso.qtbigdata.com/sso/action/goLogin?retUrl=
  registerUrl: http://sso.qtbigdata.com/sso/action/goRegister?retUrl=
  callback: http://jytest.qtbigdata.com/callback

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  soTimeout: 1501
  connectTimeout: 601
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 192.168.36.39:22122
    #- 192.168.36.39:22123
  pool:
      #从池中借出的对象的最大数目
      maxTotal: 153
      #获取连接时的最大等待毫秒数100
      maxWaitMillis: 102

# fdfs upload 文件上传配置信息
fdfs-upload:
  port: 2300
  host: 192.168.36.39

# ===================================================================
# 对接支付宝
# ===================================================================

# 回调地址
# 1. returnUrl 同步，2. notifyUrl 异步, 3. alipayPublicKey 支付宝的公钥 , 4. privateKey 商户的私钥 , 5. sellerId 收款支付宝账号, 6. partner 合作身份者ID，签约账号
# 7. signType 签名方式, 8. logPath 创建TXT日志文件夹路径, 9. inputCharset 字符编码格式, 10. paymentType 支付类型, 11. service 调用的接口名
alipay:
  returnUrl: http://jytest.qtbigdata.com/alipay/returnUrl
  notifyUrl: http://andyhttp.iok.la:23918/api/trade/alipay/toNotifyUrl
#  alipayPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCnxj/9qwVfgoUh/y2W89L6BkRAFljhNhgPdyPuBV64bfQNN1PjbCzkIM6qRdKBoLPXmKKMiFYnkd6rAoprih3/PrQEB/VsW8OoM8fxn67UDYuyBTqA23MML9q1+ilIZwBC2AQ2UBVOrFXfFl75p6/B5KsiNG9zpgmLCUYuLkxpLQIDAQAB
#  privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAOwA7AqP0Z+pXhd0eohPuY+xFQgm0Bf23GLx5X1ARdrrXaUzcoAozIexy05ZaBr+YH4fffMKvZf2fzpRDbiFvV+Be+vgMxN9hczgTOJ1wiAI2BDwULP9YxKLORdgNiPprfDeQPXN83NCWRvWt+cCp9ldp94bodqYFy3QWzS5vgUrAgMBAAECgYAr0kwB9gx9cgx3nHg4IV2aUc5O8i4HlR38/V+YbzvJV5TO3QuwwmKf+6J9jNpo0L0IDj7rxx3HPs0G/g/nKGYuH2u/xtU9a1hHDA5fMeyLPK6Klic2loPNMJomW1KJaz2OYiOSkClstTRf2AibiwtG0RmdRFByCXWmm9xTmI9DkQJBAPYwm9zOWDcGqG2Xj6gAxQX2jvEd+QoOhy8Xg1oonnmOzKSWRoEJnpvgmvEdqqaHD1bfA5Eg+aNLaTVyB1U+OEkCQQD1aGcUI32E8OcODuTbmmmbMaHf226SFrkAdy3LbL2MasGxryE+JUi9lrYyOyLZaFbR00Jhp8+aR7IlFWidQpnTAkBiFvwC/jQnuH9jKwAR8DyQI6zQZSDU4PT7zmKHiaeax0rCSR3OTAbmFJeneiqEL0vtUO4a5QiSB3nj0Ysaa7ABAkEAimzsj+CBAcb9HeHq17Be12qEm4fj88WbbxbKnw9kT9s8DKTzhGF1iXOErArNWoLPTiXzMLB+mtDMPLy5uNMDfwJBAPMtAe8tLJrAKkFEfOy0P+bwdri5ThVG9JYsogyczubgtgbYleMHjXnrb0S50FMuUklxIGh+CHbat0UaWcPDkls=
#  sellerId: 2088221727788503
#  partner: 2088221727788503
#  signType: RSA
#  logPath: C:\
#  paymentType: 1
#  service: create_direct_pay_by_user